/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import bd.OperacionesBD;
import java.io.IOException;
import impresora.PrintPDF;
import ticket.Number;

/**
 * @author Pablo
 * @author Adri
 */
public class Ticket extends javax.swing.JFrame {

    String referencia;
    PrintPDF impresora;

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    public Ticket(String nombre, String usuario, String clase, String tipo, String edad, String destino, String precio, String hora) {
        initComponents();

        referencia = Number.id_Alf_Num();

        jlblNombreR.setText(nombre);
        jlblUsuarioR.setText(usuario);
        jlblClaseR.setText(clase);
        jlblTipoR.setText(tipo);
        jlblEdadR.setText(edad);
        jlblOrigenR.setText("Vigo");
        jlblDestinoR.setText(destino);
        jlblPrecioR.setText(precio);
        jlblHoraFechaR.setText(hora);
        jlblAsientoR.setText(String.valueOf(Number.GenerarAsiento()));
        jlblTicketR.setText(String.valueOf(Number.GenerarTicket()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTipo3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblClase = new javax.swing.JLabel();
        jlblTipo = new javax.swing.JLabel();
        jlblEdad = new javax.swing.JLabel();
        jlblAsiento = new javax.swing.JLabel();
        jlblTicket = new javax.swing.JLabel();
        jlblOrigen = new javax.swing.JLabel();
        jlblDestino = new javax.swing.JLabel();
        jlblClaseR = new javax.swing.JLabel();
        jlblTipoR = new javax.swing.JLabel();
        jlblEdadR = new javax.swing.JLabel();
        jlblAsientoR = new javax.swing.JLabel();
        jlblOrigenR = new javax.swing.JLabel();
        jlblDestinoR = new javax.swing.JLabel();
        jlblTicketR = new javax.swing.JLabel();
        jlblPrecio = new javax.swing.JLabel();
        jlblPrecioR = new javax.swing.JLabel();
        jlblHoraFecha = new javax.swing.JLabel();
        jlblHoraFechaR = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jlblNombreR = new javax.swing.JLabel();
        jlblUsuario = new javax.swing.JLabel();
        jlblUsuarioR = new javax.swing.JLabel();
        jButtonConfirmarVIaje = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        jlblTipo3.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblTipo3.setText("Nº Ticket:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 203, 196));

        jPanel1.setBackground(new java.awt.Color(102, 203, 196));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ticket.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlblClase.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblClase.setText("Clase:");

        jlblTipo.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblTipo.setText("Tipo:");

        jlblEdad.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblEdad.setText("Edad:");

        jlblAsiento.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblAsiento.setText("Asiento:");

        jlblTicket.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblTicket.setText("Nº Ticket:");

        jlblOrigen.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblOrigen.setText("Origen:");

        jlblDestino.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblDestino.setText("Destino:");

        jlblClaseR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblClaseR.setText("jLabel1");

        jlblTipoR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblTipoR.setText("jLabel1");

        jlblEdadR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblEdadR.setText("jLabel1");

        jlblAsientoR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblAsientoR.setText("jLabel1");

        jlblOrigenR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblOrigenR.setText("jLabel1");

        jlblDestinoR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblDestinoR.setText("jLabel1");

        jlblTicketR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblTicketR.setText("jLabel1");

        jlblPrecio.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblPrecio.setText("Precio: ");

        jlblPrecioR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblPrecioR.setText("jLabel1");

        jlblHoraFecha.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblHoraFecha.setText("Hora y Fecha:");

        jlblHoraFechaR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblHoraFechaR.setText("jLabel1");

        jlblNombre.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblNombre.setText("Nombre:");

        jlblNombreR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblNombreR.setText("jLabel1");

        jlblUsuario.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jlblUsuario.setText("Usuario:");

        jlblUsuarioR.setFont(new java.awt.Font("MACGrande Medium", 1, 12)); // NOI18N
        jlblUsuarioR.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblClase)
                    .addComponent(jlblAsiento)
                    .addComponent(jlblTicket)
                    .addComponent(jlblClaseR)
                    .addComponent(jlblAsientoR)
                    .addComponent(jlblTicketR)
                    .addComponent(jlblPrecioR)
                    .addComponent(jlblPrecio)
                    .addComponent(jlblNombre)
                    .addComponent(jlblNombreR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblUsuario)
                    .addComponent(jlblUsuarioR)
                    .addComponent(jlblHoraFecha)
                    .addComponent(jlblHoraFechaR)
                    .addComponent(jlblDestino)
                    .addComponent(jlblOrigen)
                    .addComponent(jlblDestinoR)
                    .addComponent(jlblOrigenR)
                    .addComponent(jlblTipo)
                    .addComponent(jlblTipoR))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEdad)
                    .addComponent(jlblEdadR))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblNombreR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblUsuarioR)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblClase)
                    .addComponent(jlblTipo)
                    .addComponent(jlblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblClaseR)
                    .addComponent(jlblTipoR)
                    .addComponent(jlblEdadR))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAsiento)
                    .addComponent(jlblOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAsientoR)
                    .addComponent(jlblOrigenR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTicket)
                    .addComponent(jlblDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDestinoR)
                    .addComponent(jlblTicketR))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblPrecioR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblHoraFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblHoraFechaR)))
                .addGap(22, 22, 22))
        );

        jButtonConfirmarVIaje.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jButtonConfirmarVIaje.setText("CREAR");
        jButtonConfirmarVIaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmarVIajeMouseClicked(evt);
            }
        });

        jButtonCerrar.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jButtonCerrar.setText("SALIR");
        jButtonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmarVIaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrar)
                    .addComponent(jButtonConfirmarVIaje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarMouseClicked
        setVisible(false);
    }//GEN-LAST:event_jButtonCerrarMouseClicked
FileChooser visualizar = new FileChooser();
    private void jButtonConfirmarVIajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmarVIajeMouseClicked
           visualizar.setVisible(true);
           this.impresion();

    }//GEN-LAST:event_jButtonConfirmarVIajeMouseClicked

    //NUEVO METODO
    public void impresion(){
        
        String nombre = jlblNombre.getText();
        String nombreR = jlblNombreR.getText();
        String usuario = jlblUsuario.getText();
        String usuarioR = jlblUsuarioR.getText();
        String clase = jlblClase.getText();
        String claseR = jlblClaseR.getText();
        String tipo = jlblTipo.getText();
        String tipoR = jlblTipoR.getText();
        String edad = jlblEdad.getText();
        String edadR = jlblEdadR.getText();
        String asiento = jlblAsiento.getText();
        String asientoR = jlblAsientoR.getText();
        String origen = jlblOrigen.getText();
        String origenR = jlblOrigenR.getText();
        String ticket = jlblTicket.getText();
        String ticketR = jlblTicketR.getText();
        String destino = jlblDestino.getText();
        String destinoR = jlblDestinoR.getText();
        String precio = jlblPrecio.getText();
        String precioR = jlblPrecioR.getText();
        String hora = jlblHoraFecha.getText();
        String horaR = jlblHoraFechaR.getText();

        try {
                    
            impresora = new PrintPDF();
            impresora.setNombreArchivo(referencia);
            // Cabecera
            impresora.imprimeTexto("Vigo Bus Ticket", 300, 710, 32, "negrita");
            impresora.imprimeImagen(70, 650);
            // Cuerpo: titulos
            impresora.imprimeTexto(nombre, 50, 600, 16, "normal");
            impresora.imprimeTexto(usuario, 250, 600, 16, "normal");
            impresora.imprimeTexto(clase, 50, 500, 16, "normal");
            impresora.imprimeTexto(tipo, 250, 500, 16, "normal");
            impresora.imprimeTexto(edad, 450, 500, 16, "normal");
            impresora.imprimeTexto(asiento, 50, 400, 16, "normal");
            impresora.imprimeTexto(origen, 250, 400, 16, "normal");
            impresora.imprimeTexto(ticket, 50, 300, 16, "normal");
            impresora.imprimeTexto(destino, 250, 300, 16, "normal");
            impresora.imprimeTexto(precio, 50, 200, 16, "normal");
            impresora.imprimeTexto(hora, 250, 200, 16, "normal");
            // Cuerpo: resultados
            impresora.imprimeTexto(nombreR, 50, 550, 13, "normal");
            impresora.imprimeTexto(usuarioR, 250, 550, 13, "normal");
            impresora.imprimeTexto(claseR, 50, 450, 13, "normal");
            impresora.imprimeTexto(tipoR, 250, 450, 13, "normal");
            impresora.imprimeTexto(edadR, 450, 450, 13, "normal");
            impresora.imprimeTexto(origenR, 250, 350, 13, "normal");
            impresora.imprimeTexto(asientoR, 50, 350, 13, "normal");
            impresora.imprimeTexto(destinoR, 250, 250, 13, "normal");
            impresora.imprimeTexto(ticketR, 50, 250, 13, "normal");
            impresora.imprimeTexto(precioR, 50, 150, 13, "normal");
            impresora.imprimeTexto(horaR, 250, 150, 13, "normal");
            // Cerramos el stream
            impresora.cerrarContenido();

            
            visualizar.confirmacion(impresora);
            //Inserccion en base
            OperacionesBD sql= new OperacionesBD();
//            sql.insertViaje(sql., bus);
            

        } catch (IOException e) {

            System.out.println(e.getMessage());

        }

        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonConfirmarVIaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlblAsiento;
    private javax.swing.JLabel jlblAsientoR;
    private javax.swing.JLabel jlblClase;
    private javax.swing.JLabel jlblClaseR;
    private javax.swing.JLabel jlblDestino;
    private javax.swing.JLabel jlblDestinoR;
    private javax.swing.JLabel jlblEdad;
    private javax.swing.JLabel jlblEdadR;
    private javax.swing.JLabel jlblHoraFecha;
    private javax.swing.JLabel jlblHoraFechaR;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblNombreR;
    private javax.swing.JLabel jlblOrigen;
    private javax.swing.JLabel jlblOrigenR;
    private javax.swing.JLabel jlblPrecio;
    private javax.swing.JLabel jlblPrecioR;
    private javax.swing.JLabel jlblTicket;
    private javax.swing.JLabel jlblTicketR;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTipo3;
    private javax.swing.JLabel jlblTipoR;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JLabel jlblUsuarioR;
    // End of variables declaration//GEN-END:variables
}
